// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: debit_recovery.proto

#include "debit_recovery.pb.h"
#include "debit_recovery.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace axis {
namespace transactions {

static const char* RecoverDebitService_method_names[] = {
  "/axis.transactions.RecoverDebitService/Recover",
};

std::unique_ptr< RecoverDebitService::Stub> RecoverDebitService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RecoverDebitService::Stub> stub(new RecoverDebitService::Stub(channel, options));
  return stub;
}

RecoverDebitService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Recover_(RecoverDebitService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RecoverDebitService::Stub::Recover(::grpc::ClientContext* context, const ::axis::transactions::DebitRecoveryRequest& request, ::axis::transactions::DebitRecoveryResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::axis::transactions::DebitRecoveryRequest, ::axis::transactions::DebitRecoveryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Recover_, context, request, response);
}

void RecoverDebitService::Stub::async::Recover(::grpc::ClientContext* context, const ::axis::transactions::DebitRecoveryRequest* request, ::axis::transactions::DebitRecoveryResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::axis::transactions::DebitRecoveryRequest, ::axis::transactions::DebitRecoveryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Recover_, context, request, response, std::move(f));
}

void RecoverDebitService::Stub::async::Recover(::grpc::ClientContext* context, const ::axis::transactions::DebitRecoveryRequest* request, ::axis::transactions::DebitRecoveryResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Recover_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::axis::transactions::DebitRecoveryResponse>* RecoverDebitService::Stub::PrepareAsyncRecoverRaw(::grpc::ClientContext* context, const ::axis::transactions::DebitRecoveryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::axis::transactions::DebitRecoveryResponse, ::axis::transactions::DebitRecoveryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Recover_, context, request);
}

::grpc::ClientAsyncResponseReader< ::axis::transactions::DebitRecoveryResponse>* RecoverDebitService::Stub::AsyncRecoverRaw(::grpc::ClientContext* context, const ::axis::transactions::DebitRecoveryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRecoverRaw(context, request, cq);
  result->StartCall();
  return result;
}

RecoverDebitService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RecoverDebitService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RecoverDebitService::Service, ::axis::transactions::DebitRecoveryRequest, ::axis::transactions::DebitRecoveryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RecoverDebitService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::axis::transactions::DebitRecoveryRequest* req,
             ::axis::transactions::DebitRecoveryResponse* resp) {
               return service->Recover(ctx, req, resp);
             }, this)));
}

RecoverDebitService::Service::~Service() {
}

::grpc::Status RecoverDebitService::Service::Recover(::grpc::ServerContext* context, const ::axis::transactions::DebitRecoveryRequest* request, ::axis::transactions::DebitRecoveryResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace axis
}  // namespace transactions

