// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: passage_register.proto

#include "passage_register.pb.h"
#include "passage_register.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace axis {
namespace transactions {

static const char* Transactions_method_names[] = {
  "/axis.transactions.Transactions/MakeTransaction",
};

std::unique_ptr< Transactions::Stub> Transactions::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Transactions::Stub> stub(new Transactions::Stub(channel));
  return stub;
}

Transactions::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_MakeTransaction_(Transactions_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Transactions::Stub::MakeTransaction(::grpc::ClientContext* context, const ::axis::transactions::RegisterPassage& request, ::axis::transactions::RegisterPassageResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_MakeTransaction_, context, request, response);
}

void Transactions::Stub::experimental_async::MakeTransaction(::grpc::ClientContext* context, const ::axis::transactions::RegisterPassage* request, ::axis::transactions::RegisterPassageResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_MakeTransaction_, context, request, response, std::move(f));
}

void Transactions::Stub::experimental_async::MakeTransaction(::grpc::ClientContext* context, const ::axis::transactions::RegisterPassage* request, ::axis::transactions::RegisterPassageResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_MakeTransaction_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::axis::transactions::RegisterPassageResponse>* Transactions::Stub::PrepareAsyncMakeTransactionRaw(::grpc::ClientContext* context, const ::axis::transactions::RegisterPassage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::axis::transactions::RegisterPassageResponse>::Create(channel_.get(), cq, rpcmethod_MakeTransaction_, context, request, false);
}

::grpc::ClientAsyncResponseReader< ::axis::transactions::RegisterPassageResponse>* Transactions::Stub::AsyncMakeTransactionRaw(::grpc::ClientContext* context, const ::axis::transactions::RegisterPassage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMakeTransactionRaw(context, request, cq);
  result->StartCall();
  return result;
}

Transactions::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Transactions_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Transactions::Service, ::axis::transactions::RegisterPassage, ::axis::transactions::RegisterPassageResponse>(
          [](Transactions::Service* service,
             ::grpc::ServerContext* ctx,
             const ::axis::transactions::RegisterPassage* req,
             ::axis::transactions::RegisterPassageResponse* resp) {
               return service->MakeTransaction(ctx, req, resp);
             }, this)));
}

Transactions::Service::~Service() {
}

::grpc::Status Transactions::Service::MakeTransaction(::grpc::ServerContext* context, const ::axis::transactions::RegisterPassage* request, ::axis::transactions::RegisterPassageResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace axis
}  // namespace transactions

